import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-weddly-manager','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
function secretKey(){const secrets=Deno.env.get('SUPABASE_SECRET_KEYS');return secrets?JSON.parse(secrets).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''}
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false}})}
async function sha256(value:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function norm(v:unknown){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'')}
function secretCode(product:string){const p=product==='guests'?'WSDG':product==='payments'?'WSDP':'WSDF',a=crypto.randomUUID().replaceAll('-','').toUpperCase(),b=crypto.randomUUID().replaceAll('-','').toUpperCase();return `${p}-${a.slice(0,8)}-${a.slice(8,16)}-${b.slice(0,8)}-${b.slice(8,16)}`}
function b64url(s:string){return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function unb64url(s:string){let v=s.replaceAll('-','+').replaceAll('_','/');while(v.length%4)v+='=';return atob(v)}
async function hmac(data:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secretKey()),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode('wsd-owner-manager-v1|'+data));return Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function demoMemberToken(licenseId:string,lang:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secretKey()),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`wsd-demo-member-v1|${licenseId}|${lang}`));const hex=Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,'0')).join('');return `WSDDEMO-${hex}`}
function safeEq(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function issueManager(ownerId:string){const exp=Date.now()+30*86400000,payload=b64url(JSON.stringify({v:1,ownerId,exp,nonce:crypto.randomUUID()})),sig=await hmac(payload);return{token:`v1.${payload}.${sig}`,expiresAt:new Date(exp).toISOString()}}
async function managerContext(db:any,req:Request){const token=String(req.headers.get('x-weddly-manager')||'').trim(),parts=token.split('.');if(parts.length!==3||parts[0]!=='v1')return null;const sig=await hmac(parts[1]);if(!safeEq(sig,parts[2]))return null;let p:any;try{p=JSON.parse(unb64url(parts[1]))}catch{return null}if(!p?.ownerId||!p?.exp||Date.now()>=Number(p.exp))return null;const {data:l,error}=await db.from('licenses').select('id,source,status,metadata').eq('id',String(p.ownerId)).maybeSingle();if(error)throw error;if(!l||l.source!=='internal_owner'||l.status!=='active'||l.metadata?.grant_type!=='owner')return null;return{license:l,payload:p}}
function expired(meta:any){const raw=meta?.expires_at;if(!raw)return false;const t=Date.parse(String(raw));return Number.isFinite(t)&&Date.now()>=t}
function productOf(meta:any){const p=String(meta?.product||'');if(p==='guests'||p==='full'||p==='payments')return p;if(p==='suppliers_payments')return'payments';return'payments'}
function editionOf(meta:any){return String(meta?.edition||'').toLowerCase()==='signature'?'signature':'essential'}
function weddingExpiry(settings:any){const raw=String(settings?.weddingDate||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))return null;const [y,m,d]=raw.split('-').map(Number);const ms=Date.UTC(y,m-1,d+91,0,0,0,0);return Number.isFinite(ms)?new Date(ms).toISOString():null}
async function validateRecovery(db:any,raw:any){const code=norm(raw);if(code.length<20)return null;const hash=await sha256(code);const {data:l,error}=await db.from('licenses').select('id,source,status,metadata').eq('purchase_hash',hash).eq('source','internal_owner').eq('status','active').maybeSingle();if(error)throw error;if(!l||l.metadata?.grant_type!=='owner')return null;return l}
async function ensureStableDemoMember(db:any,l:any,lang:string){const token=await demoMemberToken(String(l.id),lang),hash=await sha256(token),now=new Date().toISOString();const {data:m,error:me}=await db.from('wedding_members').select('id').eq('license_id',l.id).eq('role','partner').maybeSingle();if(me)throw me;if(m?.id){const {error}=await db.from('wedding_members').update({member_hash:hash,status:'active',wedding_id:l.wedding_id,last_seen_at:now}).eq('id',m.id);if(error)throw error}else{const {error}=await db.from('wedding_members').insert({license_id:l.id,wedding_id:l.wedding_id,role:'partner',member_hash:hash,status:'active',last_seen_at:now});if(error)throw error}return token}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const text=await req.text();if(text.length>32768)return json({ok:false,error:'body_too_large'},413);let b:any={};try{b=JSON.parse(text||'{}')}catch{return json({ok:false,error:'invalid_json'},400)}const db=admin(),action=String(b.action||'');
if(action==='login'){const owner=await validateRecovery(db,b.recoveryCode);if(!owner)return json({ok:false,error:'invalid_recovery'},403);const session=await issueManager(owner.id);return json({ok:true,managerToken:session.token,expiresAt:session.expiresAt})}
const ctx=await managerContext(db,req);if(!ctx)return json({ok:false,error:'manager_required'},403);
if(action==='status')return json({ok:true,expiresAt:new Date(Number(ctx.payload.exp)).toISOString()});
if(action==='demo_token'){const lang=String(b.lang||'').toLowerCase();if(lang!=='es'&&lang!=='en')return json({ok:false,error:'invalid_lang'},400);const {data:l,error:le}=await db.from('licenses').select('id,wedding_id,status').eq('source','internal_demo').eq('status','active').eq('metadata->>demo_lang',lang).maybeSingle();if(le)throw le;if(!l?.id||!l?.wedding_id)return json({ok:false,error:'demo_not_configured'},404);const token=await ensureStableDemoMember(db,l,lang);return json({ok:true,lang,memberToken:token,weddingId:l.wedding_id,stable:true})}
if(action==='list'){const {data:rows,error}=await db.from('licenses').select('id,source,status,wedding_id,metadata,created_at,activated_at').eq('source','tester').order('created_at',{ascending:false}).limit(100);if(error)throw error;const ids=(rows||[]).map((x:any)=>x.id),wids=[...new Set((rows||[]).map((x:any)=>x.wedding_id).filter(Boolean))];let counts=new Map<string,number>(),weddings=new Map<string,any>();if(ids.length){const {data:members,error:me}=await db.from('wedding_members').select('license_id,status').in('license_id',ids).eq('status','active');if(me)throw me;for(const m of members||[])counts.set(String(m.license_id),(counts.get(String(m.license_id))||0)+1)}if(wids.length){const {data:ws,error:we}=await db.from('weddings').select('id,settings').in('id',wids);if(we)throw we;for(const w of ws||[])weddings.set(String(w.id),w.settings||{})}return json({ok:true,testers:(rows||[]).map((x:any)=>{const meta=x.metadata||{},product=productOf(meta),weddingExpiresAt=meta.permanent===true&&product==='full'?weddingExpiry(weddings.get(String(x.wedding_id))||{}):null,effectiveExpiresAt=meta.expires_at||weddingExpiresAt||null,isExpired=x.status!=='active'||expired(meta)||(!!weddingExpiresAt&&Date.now()>=Date.parse(weddingExpiresAt));return{id:x.id,status:x.status,label:meta.tester_label||'',product,edition:editionOf(meta),permanent:meta.permanent===true,trialDays:meta.trial_days||null,createdAt:x.created_at,activatedAt:x.activated_at,expiresAt:effectiveExpiresAt,expiryRule:meta.permanent===true&&product==='full'?'wedding_plus_90':(meta.expires_at?'fixed':null),expired:isExpired,activeMembers:counts.get(String(x.id))||0}})})}
if(action==='grant'){const product=String(b.product||'');if(!['payments','guests','full'].includes(product))return json({ok:false,error:'invalid_product'},400);const kind=String(b.kind||'');if(!['permanent','7','14'].includes(kind))return json({ok:false,error:'invalid_kind'},400);const edition=product==='full'&&String(b.edition||'').toLowerCase()==='signature'?'signature':'essential',label=String(b.label||'').trim().slice(0,120),permanent=kind==='permanent',days=permanent?null:Number(kind),expiresAt=permanent?null:new Date(Date.now()+Number(days)*86400000).toISOString(),code=secretCode(product),hash=await sha256(norm(code)),orderId=`tester:${product}:${crypto.randomUUID()}`,meta:any={grant_type:'tester',permanent,product,edition,access_kind:permanent?'free_tester':'trial',granted_by:'owner_manager_v1',granted_at:new Date().toISOString()};if(label)meta.tester_label=label;if(permanent&&product==='full')meta.access_window='wedding_plus_90';if(!permanent){meta.trial_days=days;meta.expires_at=expiresAt}const ref=`${product}_${edition}_${permanent?'free':'trial_'+days}`;const {data,error}=await db.rpc('provision_weddly_license',{p_source:'tester',p_source_order_id:orderId,p_buyer_email:null,p_product_ref:ref,p_metadata:meta,p_activation_code:code,p_purchase_hash:hash});if(error)throw error;const row=data?.[0];if(!row?.license_id||!row?.activation_code)return json({ok:false,error:'server_error'},500);const testerLink=`https://weddlysmartdesign.github.io/tester-access.html?product=${product}&v=5#tester=${encodeURIComponent(String(row.activation_code))}`;return json({ok:true,licenseId:row.license_id,activationCode:row.activation_code,testerLink,product,edition,kind,expiresAt,expiryRule:permanent&&product==='full'?'wedding_plus_90':(expiresAt?'fixed':null)},201)}
if(action==='set_edition'){const licenseId=String(b.licenseId||'').trim(),edition=String(b.edition||'').toLowerCase();if(!licenseId||!['essential','signature'].includes(edition))return json({ok:false,error:'invalid_request'},400);const {data:l,error:le}=await db.from('licenses').select('id,source,status,wedding_id,metadata').eq('id',licenseId).eq('source','tester').maybeSingle();if(le)throw le;if(!l)return json({ok:false,error:'invalid_license'},404);if(l.status!=='active'||expired(l.metadata))return json({ok:false,error:'license_inactive'},403);const meta=l.metadata||{};if(productOf(meta)!=='full')return json({ok:false,error:'full_required'},400);const next={...meta,edition,edition_updated_at:new Date().toISOString(),edition_updated_by:'owner_manager_v1'};const {error:ue}=await db.from('licenses').update({metadata:next,updated_at:new Date().toISOString()}).eq('id',l.id).eq('status','active');if(ue)throw ue;return json({ok:true,licenseId:l.id,edition,sameWedding:!!l.wedding_id})}
if(action==='reissue'){const licenseId=String(b.licenseId||'').trim();if(!licenseId)return json({ok:false,error:'invalid_license'},400);const {data:l,error:le}=await db.from('licenses').select('id,source,status,wedding_id,metadata,activated_at').eq('id',licenseId).eq('source','tester').maybeSingle();if(le)throw le;if(!l)return json({ok:false,error:'invalid_license'},404);if(l.status!=='active')return json({ok:false,error:'license_inactive'},403);if(expired(l.metadata)){await db.from('licenses').update({status:'inactive',updated_at:new Date().toISOString()}).eq('id',l.id).eq('status','active');return json({ok:false,error:'license_expired'},410)}const product=productOf(l.metadata||{}),code=secretCode(product),hash=await sha256(norm(code)),meta={...(l.metadata||{}),reissued_at:new Date().toISOString(),reissued_by:'owner_manager_v1'};const {error:ue}=await db.from('licenses').update({purchase_hash:hash,metadata:meta,updated_at:new Date().toISOString()}).eq('id',l.id).eq('source','tester');if(ue)throw ue;const testerLink=`https://weddlysmartdesign.github.io/tester-access.html?product=${product}&v=5#tester=${encodeURIComponent(code)}`;return json({ok:true,testerLink,product,activated:!!l.activated_at,sameWedding:!!l.wedding_id},201)}
if(action==='recovery_code'){const {data:d,error}=await db.from('license_delivery_codes').select('activation_code').eq('license_id',ctx.license.id).maybeSingle();if(error)throw error;if(!d?.activation_code)return json({ok:false,error:'recovery_code_missing'},404);return json({ok:true,activationCode:d.activation_code})}
return json({ok:false,error:'invalid_action'},400)}catch(e){console.error(e);return json({ok:false,error:'server_error'},500)}});