const fs=require('fs'),path=require('path');const ok=(x,m)=>{if(!x)throw new Error(m)};
const root=path.resolve(__dirname,'..','..');
const backend=fs.readFileSync(path.join(root,'guest','backend','guest-stripe-checkout','index.ts'),'utf8');
const checkout=fs.readFileSync(path.join(root,'guest-checkout.html'),'utf8');
const ret=fs.readFileSync(path.join(root,'guest-checkout-return.html'),'utf8');
const order=fs.readFileSync(path.join(root,'guest-order.html'),'utf8');
const deliver=fs.readFileSync(path.join(root,'guest-deliver.html'),'utf8');
ok(backend.includes("guest-stripe-checkout/")+backend.includes("idempotency_key"),'Stripe session create must be idempotent');
ok(backend.includes("guest-order-internal/")+backend.includes("guest-order-confirm/"),'order emails need idempotency keys');
ok(backend.includes("guest-access-delivery/"),'delivery email needs idempotency key');
ok(backend.includes("guest_access_delivered_at"),'duplicate delivery guard missing');
ok(backend.includes("guest_order_submitted_at"),'duplicate order guard missing');
for(const e of ['order_not_submitted','invalid_delivery_token','already_activated','delivery_email_failed'])ok(backend.includes(e),'missing recoverable error '+e);
ok(/catch\(e\)/.test(checkout)&&/err|error|msg/i.test(checkout),'checkout has no visible failure path');
ok(ret.includes('reintentar')||ret.includes('Reintentar'),'return has no retry path');
ok(order.includes('No hemos podido')||order.includes('reintentar')||order.includes('Reintentar'),'order has no recovery message');
ok(deliver.includes('reintentar'),'delivery has no retry guidance');
ok(deliver.includes('b.disabled=true'),'delivery does not prevent double-click while sending');
console.log('B8.5 error retry duplicate contract: PASS');