import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-weddly-member','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
function secretKey(){const secrets=Deno.env.get('SUPABASE_SECRET_KEYS');return secrets?JSON.parse(secrets).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''}
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false}})}
async function sha256(value:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function demoMemberToken(licenseId:string,lang:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secretKey()),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`wsd-demo-member-v1|${licenseId}|${lang}`));const hex=Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,'0')).join('');return `WSDDEMO-${hex}`}
function secretCode(product:string){const p=product==='guests'?'WSDG':product==='payments'?'WSDP':'WSDF',a=crypto.randomUUID().replaceAll('-','').toUpperCase(),b=crypto.randomUUID().replaceAll('-','').toUpperCase();return `${p}-${a.slice(0,8)}-${a.slice(8,16)}-${b.slice(0,8)}-${b.slice(8,16)}`}
function norm(v:unknown){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'')}
async function body(req:Request){const t=await req.text();if(t.length>32768)throw new Error('body_too_large');try{return JSON.parse(t||'{}')}catch{throw new Error('invalid_json')}}
function expired(meta:any){const raw=meta?.expires_at;if(!raw)return false;const t=Date.parse(String(raw));return Number.isFinite(t)&&Date.now()>=t}
function weddingWindowEligible(source:string,meta:any){return String(meta?.product||'')==='full'&&(String(meta?.access_kind||'')==='paid'||(source==='tester'&&meta?.permanent===true))}
function weddingExpiry(settings:any){const raw=String(settings?.weddingDate||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))return null;const [y,m,d]=raw.split('-').map(Number);const ms=Date.UTC(y,m-1,d+91,0,0,0,0);return Number.isFinite(ms)?new Date(ms).toISOString():null}
async function weddingExpired(db:any,l:any){if(!l?.wedding_id||!weddingWindowEligible(String(l.source||''),l.metadata||{}))return false;const {data:w,error}=await db.from('weddings').select('settings').eq('id',l.wedding_id).maybeSingle();if(error)throw error;const exp=weddingExpiry(w?.settings||{});return !!exp&&Date.now()>=Date.parse(exp)}
function isOwnerLicense(source:string,meta:any){return source==='internal_owner'&&meta?.grant_type==='owner'}
function productOf(source:string,meta:any){if(isOwnerLicense(source,meta))return'full';const p=String(meta?.product||'');if(p==='guests'||p==='full'||p==='payments')return p;if(p==='suppliers_payments')return'payments';return'payments'}
function editionOf(source:string,meta:any){if(isOwnerLicense(source,meta))return'signature';return String(meta?.edition||'').toLowerCase()==='signature'?'signature':'essential'}
async function context(db:any,req:Request,b:any){const token=String(req.headers.get('x-weddly-member')||b?.memberToken||'').trim();if(token.length<40)return null;const hash=await sha256(token);const {data:m,error:me}=await db.from('wedding_members').select('id,wedding_id,license_id,role,status').eq('member_hash',hash).eq('status','active').maybeSingle();if(me)throw me;if(!m)return null;const {data:l,error:le}=await db.from('licenses').select('id,source,status,wedding_id,metadata,created_at,activated_at').eq('id',m.license_id).maybeSingle();if(le)throw le;if(!l||l.status!=='active'||l.wedding_id!==m.wedding_id)return null;if((l.source==='tester'&&expired(l.metadata))||await weddingExpired(db,l)){const now=new Date().toISOString(),metadata={...(l.metadata||{}),deactivated_reason:(l.source==='tester'&&expired(l.metadata))?'trial_expired':'wedding_plus_90',deactivated_at:now};await db.from('licenses').update({status:'inactive',metadata,updated_at:now}).eq('id',l.id).eq('status','active');return null}return{member:m,license:l,product:productOf(String(l.source||''),l.metadata||{})}}
async function owner(db:any,req:Request,b:any){const c=await context(db,req,b);if(!c)return null;const m=c.license.metadata||{};return c.member.role==='primary'&&isOwnerLicense(String(c.license.source||''),m)?c:null}
async function ensureStableDemoMember(db:any,l:any,lang:string){const token=await demoMemberToken(String(l.id),lang),hash=await sha256(token),now=new Date().toISOString();const {data:m,error:me}=await db.from('wedding_members').select('id').eq('license_id',l.id).eq('role','partner').maybeSingle();if(me)throw me;if(m?.id){const {error}=await db.from('wedding_members').update({member_hash:hash,status:'active',wedding_id:l.wedding_id,last_seen_at:now}).eq('id',m.id);if(error)throw error}else{const {error}=await db.from('wedding_members').insert({license_id:l.id,wedding_id:l.wedding_id,role:'partner',member_hash:hash,status:'active',last_seen_at:now});if(error)throw error}return token}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const b=await body(req),action=String(b?.action||''),db=admin();
if(action==='entitlement'){const c=await context(db,req,b);if(!c)return json({ok:false,error:'invalid_access'},401);const meta=c.license.metadata||{},source=String(c.license.source||''),ownerFlag=c.member.role==='primary'&&isOwnerLicense(source,meta);return json({ok:true,product:c.product,edition:editionOf(source,meta),role:c.member.role,owner:ownerFlag,tester:c.license.source==='tester',permanent:meta.permanent===true,expiresAt:meta.expires_at||null,trialDays:meta.trial_days||null})}
if(action==='owner_status'){const c=await owner(db,req,b);if(!c)return json({ok:false,error:'owner_required'},403);return json({ok:true,owner:true,weddingId:c.member.wedding_id})}
if(action==='owner_demo_token'){const c=await owner(db,req,b);if(!c)return json({ok:false,error:'owner_required'},403);const lang=String(b.lang||'').toLowerCase();if(lang!=='es'&&lang!=='en')return json({ok:false,error:'invalid_lang'},400);const {data:l,error:le}=await db.from('licenses').select('id,wedding_id,status').eq('source','internal_demo').eq('status','active').eq('metadata->>demo_lang',lang).maybeSingle();if(le)throw le;if(!l?.id||!l?.wedding_id)return json({ok:false,error:'demo_not_configured'},404);const token=await ensureStableDemoMember(db,l,lang);return json({ok:true,lang,memberToken:token,weddingId:l.wedding_id,stable:true})}
if(action==='grant'){const c=await owner(db,req,b);if(!c)return json({ok:false,error:'owner_required'},403);const product=String(b.product||'');if(!['payments','guests','full'].includes(product))return json({ok:false,error:'invalid_product'},400);const kind=String(b.kind||'');if(!['permanent','7','14'].includes(kind))return json({ok:false,error:'invalid_kind'},400);const label=String(b.label||'').trim().slice(0,120),permanent=kind==='permanent',days=permanent?null:Number(kind),expiresAt=permanent?null:new Date(Date.now()+Number(days)*86400000).toISOString(),code=secretCode(product),hash=await sha256(norm(code)),orderId=`tester:${product}:${crypto.randomUUID()}`,meta:any={grant_type:'tester',permanent,product,access_kind:permanent?'free_tester':'trial',granted_by:'owner_portal_v3',granted_at:new Date().toISOString()};if(label)meta.tester_label=label;if(!permanent){meta.trial_days=days;meta.expires_at=expiresAt}const ref=`${product}_${permanent?'free':'trial_'+days}`;const {data,error}=await db.rpc('provision_weddly_license',{p_source:'tester',p_source_order_id:orderId,p_buyer_email:null,p_product_ref:ref,p_metadata:meta,p_activation_code:code,p_purchase_hash:hash});if(error)throw error;const row=data?.[0];if(!row?.license_id||!row?.activation_code)return json({ok:false,error:'server_error'},500);const testerLink=`https://weddlysmartdesign.github.io/tester-access.html?product=${product}&v=2#tester=${encodeURIComponent(String(row.activation_code))}`;return json({ok:true,licenseId:row.license_id,activationCode:row.activation_code,testerLink,product,kind,expiresAt},201)}
if(action==='list'){const c=await owner(db,req,b);if(!c)return json({ok:false,error:'owner_required'},403);const {data:rows,error}=await db.from('licenses').select('id,source,status,wedding_id,metadata,created_at,activated_at').eq('source','tester').order('created_at',{ascending:false}).limit(100);if(error)throw error;const ids=(rows||[]).map((x:any)=>x.id);let counts=new Map<string,number>();if(ids.length){const {data:members,error:me}=await db.from('wedding_members').select('license_id,status').in('license_id',ids).eq('status','active');if(me)throw me;for(const m of members||[])counts.set(String(m.license_id),(counts.get(String(m.license_id))||0)+1)}return json({ok:true,testers:(rows||[]).map((x:any)=>{const meta=x.metadata||{};return{id:x.id,status:x.status,label:meta.tester_label||'',product:productOf('tester',meta),permanent:meta.permanent===true,trialDays:meta.trial_days||null,createdAt:x.created_at,activatedAt:x.activated_at,expiresAt:meta.expires_at||null,expired:expired(meta),activeMembers:counts.get(String(x.id))||0}})})}
return json({ok:false,error:'invalid_action'},400)}catch(e){const m=String((e as Error)?.message||'');console.error(e);if(m==='body_too_large')return json({ok:false,error:m},413);if(m==='invalid_json')return json({ok:false,error:m},400);return json({ok:false,error:'server_error'},500)}});