import { createClient } from 'npm:@supabase/supabase-js@2';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-weddly-member','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
function admin(){const secrets=Deno.env.get('SUPABASE_SECRET_KEYS');const key=secrets?JSON.parse(secrets).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');return createClient(Deno.env.get('SUPABASE_URL')!,key!,{auth:{persistSession:false}})}
function envClean(name:string){let v=(Deno.env.get(name)||'').trim();if(v.length>=2){const a=v[0],b=v[v.length-1];if((a==='"'&&b==='"')||(a==="'"&&b==="'")||(a==='`'&&b==='`'))v=v.slice(1,-1).trim()}return v}
async function sha256(value:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function secret(){return crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','')}
function activationCode(){const a=crypto.randomUUID().replaceAll('-','').toUpperCase(),b=crypto.randomUUID().replaceAll('-','').toUpperCase();return `WSD-${a.slice(0,8)}-${a.slice(8,16)}-${b.slice(0,8)}-${b.slice(8,16)}`}
function purchaseCode(v:unknown){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'')}
function email(v:unknown){return String(v||'').trim().toLowerCase().slice(0,254)}
async function body(req:Request){const text=await req.text();if(text.length>32768)throw new Error('body_too_large');try{return JSON.parse(text||'{}')}catch{throw new Error('invalid_json')}}
function fixedTrialExpired(source:string,metadata:any){if(source!=='tester'||metadata?.permanent===true)return false;const raw=metadata?.expires_at;if(!raw)return false;const t=Date.parse(String(raw));return Number.isFinite(t)&&Date.now()>=t}
function weddingWindowEligible(source:string,metadata:any){if(String(metadata?.product||'')!=='full')return false;if(String(metadata?.access_kind||'')==='paid')return true;return source==='tester'&&metadata?.permanent===true}
function weddingExpiry(settings:any){const raw=String(settings?.weddingDate||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))return null;const [y,m,d]=raw.split('-').map(Number);const ms=Date.UTC(y,m-1,d+91,0,0,0,0);return Number.isFinite(ms)?new Date(ms).toISOString():null}
async function weddingWindow(db:any,l:any){if(!l?.wedding_id||!weddingWindowEligible(String(l.source||''),l.metadata||{}))return null;const {data:w,error}=await db.from('weddings').select('settings').eq('id',l.wedding_id).maybeSingle();if(error)throw error;const weddingDate=String(w?.settings?.weddingDate||'').trim(),expiresAt=weddingExpiry(w?.settings||{});if(!expiresAt)return null;return{weddingDate,expiresAt,expired:Date.now()>=Date.parse(expiresAt)}}
async function deactivateIfExpired(db:any,l:any){if(!l)return false;let reason='',expiresAt:string|null=null,weddingDate:string|null=null;if(fixedTrialExpired(String(l.source||''),l.metadata)){reason='trial_expired';expiresAt=String(l.metadata?.expires_at||'')}else{const w=await weddingWindow(db,l);if(w?.expired){reason='wedding_plus_90';expiresAt=w.expiresAt;weddingDate=w.weddingDate}}if(!reason)return false;const now=new Date().toISOString(),metadata={...(l.metadata||{}),deactivated_reason:reason,deactivated_at:now};if(expiresAt)metadata.effective_expires_at=expiresAt;if(weddingDate)metadata.wedding_date_at_expiry=weddingDate;await db.from('licenses').update({status:'inactive',metadata,updated_at:now}).eq('id',l.id).eq('status','active');return true}
function rpcError(e:any){const m=String(e?.message||'');if(m.includes('already_activated'))return json({ok:false,error:'already_activated'},409);if(m.includes('invalid_license'))return json({ok:false,error:'invalid_license'},404);if(m.includes('invalid_owner_license'))return json({ok:false,error:'invalid_license'},404);if(m.includes('invalid_member'))return json({ok:false,error:'invalid_member'},401);if(m.includes('not_primary'))return json({ok:false,error:'not_primary'},403);if(m.includes('partner_exists'))return json({ok:false,error:'partner_exists'},409);if(m.includes('invite_expired'))return json({ok:false,error:'invite_expired'},410);if(m.includes('invite_unavailable'))return json({ok:false,error:'invite_unavailable'},409);if(m.includes('invalid_invite'))return json({ok:false,error:'invalid_invite'},404);if(m.includes('license_inactive'))return json({ok:false,error:'license_inactive'},403);console.warn(e);return json({ok:false,error:'server_error'},500)}
async function activateHash(db:any,hash:string,memberToken:string,legacyToken:string){return await db.rpc('activate_weddly_license',{p_purchase_hash:hash,p_member_hash:await sha256(memberToken),p_access_hash:await sha256(legacyToken)})}
async function memberContext(db:any,req:Request,b:any){const token=String(req.headers.get('x-weddly-member')||b?.memberToken||'').trim();if(token.length<40)return null;const hash=await sha256(token);const {data:m,error}=await db.from('wedding_members').select('id,wedding_id,license_id,role,status').eq('member_hash',hash).eq('status','active').maybeSingle();if(error)throw error;if(!m)return null;const {data:l,error:le}=await db.from('licenses').select('id,source,status,wedding_id,metadata').eq('id',m.license_id).maybeSingle();if(le)throw le;if(!l||l.status!=='active')return null;if(await deactivateIfExpired(db,l))return null;return {token,member:m,license:l}}
async function ownerContext(db:any,req:Request,b:any){const c=await memberContext(db,req,b);if(!c)return null;const meta=c.license.metadata||{};if(c.member.role!=='primary'||c.license.source!=='internal_owner'||meta.grant_type!=='owner')return null;return c}
function etsyConfig(){return {keystring:envClean('ETSY_KEYSTRING')||envClean('ETSY_API_KEY'),shared:envClean('ETSY_SHARED_SECRET')}}
function etsyHeaders(cfg:ReturnType<typeof etsyConfig>,accessToken?:string){const h:Record<string,string>={'x-api-key':`${cfg.keystring}:${cfg.shared}`,'Accept':'application/json'};if(accessToken)h.Authorization=`Bearer ${accessToken}`;return h}
async function refreshEtsyConnection(db:any,cfg:ReturnType<typeof etsyConfig>,conn:any){const form=new URLSearchParams({grant_type:'refresh_token',client_id:cfg.keystring,refresh_token:String(conn.refresh_token)});const r=await fetch('https://api.etsy.com/v3/public/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json','x-api-key':`${cfg.keystring}:${cfg.shared}`},body:form.toString()});if(!r.ok){const msg=await r.text();console.warn(`etsy_refresh_${r.status}`,msg);throw new Error(`etsy_refresh_${r.status}`)}const t=await r.json();const expiresAt=new Date(Date.now()+Number(t.expires_in||3600)*1000).toISOString();const {data,error}=await db.from('etsy_connections').update({access_token:String(t.access_token),refresh_token:String(t.refresh_token||conn.refresh_token),scope:String(t.scope||conn.scope||''),expires_at:expiresAt,updated_at:new Date().toISOString()}).eq('source','etsy').select('*').single();if(error)throw error;return data}
async function getEtsyConnection(db:any){const cfg=etsyConfig();if(!cfg.keystring||!cfg.shared)return null;const {data,error}=await db.from('etsy_connections').select('*').eq('source','etsy').maybeSingle();if(error)throw error;if(!data)return null;const exp=Date.parse(String(data.expires_at));if(Number.isFinite(exp)&&exp-Date.now()>120000)return data;return await refreshEtsyConnection(db,cfg,data)}
async function etsyEnabled(db:any){const cfg=etsyConfig();if(!cfg.keystring||!cfg.shared)return false;const {count,error}=await db.from('marketplace_products').select('product_ref',{head:true,count:'exact'}).eq('source','etsy').eq('active',true);if(error)throw error;if(!(count||0))return false;return !!(await getEtsyConnection(db))}
async function fetchEtsyReceipt(db:any,orderId:string){const cfg=etsyConfig();if(!cfg.keystring||!cfg.shared)throw new Error('etsy_not_configured');const conn=await getEtsyConnection(db);if(!conn)throw new Error('etsy_not_connected');const u=`https://api.etsy.com/v3/application/shops/${encodeURIComponent(String(conn.shop_id))}/receipts/${encodeURIComponent(orderId)}`;const r=await fetch(u,{headers:etsyHeaders(cfg,String(conn.access_token))});if(r.status===404)return null;if(!r.ok){const msg=await r.text();console.warn(`etsy_receipt_${r.status}`,msg);throw new Error(`etsy_${r.status}`)}return await r.json()}
async function verifyEtsyOrder(db:any,orderId:string,buyerEmail:string){const receipt=await fetchEtsyReceipt(db,orderId);if(!receipt)return null;if(String(receipt.receipt_id)!==orderId||String(receipt.status||'').toLowerCase()!=='paid')return null;const receiptEmail=email(receipt.buyer_email||receipt.payment_email);if(!receiptEmail||receiptEmail!==buyerEmail)return null;const tx=Array.isArray(receipt.transactions)?receipt.transactions:[];const ids=[...new Set(tx.map((x:any)=>String(x?.listing_id||'')).filter(Boolean))];if(!ids.length)return null;const {data:allowed,error}=await db.from('marketplace_products').select('product_ref').eq('source','etsy').eq('active',true).in('product_ref',ids);if(error)throw error;if(!allowed?.length)return null;return {receipt,listingId:String(allowed[0].product_ref)}}
async function tryGumroad(db:any,rawKey:string){const {data:products,error}=await db.from('marketplace_products').select('product_ref').eq('source','gumroad').eq('active',true).limit(20);if(error)throw error;if(!products?.length)return null;let transportFailure=false;for(const product of products){try{const form=new URLSearchParams({product_id:String(product.product_ref),license_key:rawKey,increment_uses_count:'false'});const r=await fetch('https://api.gumroad.com/v2/licenses/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form.toString()});if(r.status===404)continue;if(!r.ok){transportFailure=true;continue}const j=await r.json().catch(()=>null);if(!j?.success||!j?.purchase)continue;const p=j.purchase;if(p.refunded||p.disputed||p.chargebacked||p.subscription_ended_at||p.subscription_cancelled_at||p.subscription_failed_at)return {blocked:true};const orderId=String(p.sale_id||p.id||p.order_number||'').trim();if(!orderId)throw new Error('gumroad_order_missing');const normalized=purchaseCode(rawKey),purchaseHash=await sha256(normalized);const meta={verified_by:'gumroad_license_api',order_number:p.order_number??null,sale_id:p.sale_id??p.id??null,currency:p.currency??null,verified_at:new Date().toISOString()};const {data:prov,error:pe}=await db.rpc('provision_weddly_license',{p_source:'gumroad',p_source_order_id:orderId,p_buyer_email:String(p.email||''),p_product_ref:String(product.product_ref),p_metadata:meta,p_activation_code:rawKey,p_purchase_hash:purchaseHash});if(pe)throw pe;return {blocked:false,hash:purchaseHash,provisioned:!!prov?.[0]}}catch(e){console.warn(e);transportFailure=true}}if(transportFailure)throw new Error('gumroad_verify_unavailable');return null}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const b=await body(req),action=String(b?.action||'');const db=admin();if(action==='marketplace_status'){const {count:g,error:ge}=await db.from('marketplace_products').select('product_ref',{head:true,count:'exact'}).eq('source','gumroad').eq('active',true);if(ge)throw ge;return json({ok:true,etsy:await etsyEnabled(db),gumroad:(g||0)>0})}
if(action==='activate'){const rawCode=String(b.activationCode||'').trim(),code=purchaseCode(rawCode);if(code.length<16)return json({ok:false,error:'invalid_license'},404);const memberToken=secret(),legacyToken=secret();let hash=await sha256(code);const {data:known,error:ke}=await db.from('licenses').select('id,source,status,wedding_id,metadata').eq('purchase_hash',hash).maybeSingle();if(ke)throw ke;if(known&&await deactivateIfExpired(db,known))return json({ok:false,error:'license_expired'},410);if(known?.source==='internal_owner'&&known?.status==='active'&&known?.wedding_id){const {data:rec,error:re}=await db.rpc('recover_weddly_owner_license',{p_purchase_hash:hash,p_member_hash:await sha256(memberToken)});if(re)return rpcError(re);const row=rec?.[0];if(!row)return json({ok:false,error:'server_error'},500);return json({ok:true,weddingId:row.wedding_id,role:'primary',memberToken,owner:true,recovered:true},201)}let activation=await activateHash(db,hash,memberToken,legacyToken);if(activation.error&&String(activation.error.message||'').includes('invalid_license')){const gumroad=await tryGumroad(db,rawCode);if(gumroad?.blocked)return json({ok:false,error:'license_inactive'},403);if(!gumroad)return json({ok:false,error:'invalid_license'},404);hash=gumroad.hash;activation=await activateHash(db,hash,memberToken,legacyToken)}if(activation.error)return rpcError(activation.error);const row=activation.data?.[0];if(!row)return json({ok:false,error:'server_error'},500);return json({ok:true,weddingId:row.wedding_id,role:'primary',memberToken},201)}
if(action==='activate_etsy'){const orderId=String(b.orderId||'').trim();const buyerEmail=email(b.email);if(!/^\d{3,30}$/.test(orderId)||!buyerEmail.includes('@'))return json({ok:false,error:'invalid_license'},404);if(!await etsyEnabled(db))return json({ok:false,error:'not_configured'},503);const verified=await verifyEtsyOrder(db,orderId,buyerEmail);if(!verified)return json({ok:false,error:'invalid_license'},404);const generated=activationCode(),meta={verified_by:'etsy_receipt_api',receipt_id:orderId,listing_id:verified.listingId,verified_at:new Date().toISOString()};const {data:prov,error:pe}=await db.rpc('provision_weddly_license',{p_source:'etsy',p_source_order_id:orderId,p_buyer_email:buyerEmail,p_product_ref:verified.listingId,p_metadata:meta,p_activation_code:generated,p_purchase_hash:await sha256(purchaseCode(generated))});if(pe)throw pe;const delivered=String(prov?.[0]?.activation_code||'');if(!delivered)throw new Error('delivery_missing');const memberToken=secret(),legacyToken=secret();const activation=await activateHash(db,await sha256(purchaseCode(delivered)),memberToken,legacyToken);if(activation.error)return rpcError(activation.error);const row=activation.data?.[0];if(!row)throw new Error('activate_missing');return json({ok:true,weddingId:row.wedding_id,role:'primary',memberToken},201)}
if(action==='owner_status'){const owner=await ownerContext(db,req,b);if(!owner)return json({ok:false,error:'owner_required'},403);return json({ok:true,weddingId:owner.member.wedding_id,owner:true})}
if(action==='owner_recovery_code'){const owner=await ownerContext(db,req,b);if(!owner)return json({ok:false,error:'owner_required'},403);const {data:d,error}=await db.from('license_delivery_codes').select('activation_code').eq('license_id',owner.license.id).maybeSingle();if(error)throw error;if(!d?.activation_code)return json({ok:false,error:'recovery_code_missing'},404);return json({ok:true,activationCode:d.activation_code})}
if(action==='grant_tester'){const owner=await ownerContext(db,req,b);if(!owner)return json({ok:false,error:'owner_required'},403);const label=String(b.label||'').trim().slice(0,120);const requested=Number(b.days);const days=requested===7?7:14;const {data,error}=await db.rpc('grant_weddly_tester_license',{p_label:label||null,p_metadata:{granted_by:'owner_portal'},p_days:days});if(error)throw error;const row=data?.[0];if(!row)return json({ok:false,error:'server_error'},500);const expiresAt=new Date(Date.now()+days*86400000).toISOString();return json({ok:true,licenseId:row.license_id,activationCode:row.activation_code,testerLink:row.tester_link,days,expiresAt},201)}
if(action==='list_testers'){const owner=await ownerContext(db,req,b);if(!owner)return json({ok:false,error:'owner_required'},403);const {data:rows,error}=await db.from('licenses').select('id,status,wedding_id,metadata,created_at,activated_at').eq('source','tester').order('created_at',{ascending:false}).limit(100);if(error)throw error;const ids=(rows||[]).map((x:any)=>x.id);let counts=new Map<string,number>();if(ids.length){const {data:members,error:me}=await db.from('wedding_members').select('license_id,status').in('license_id',ids).eq('status','active');if(me)throw me;for(const m of members||[])counts.set(String(m.license_id),(counts.get(String(m.license_id))||0)+1)}return json({ok:true,testers:(rows||[]).map((x:any)=>({id:x.id,status:x.status,label:x.metadata?.tester_label||'',createdAt:x.created_at,activatedAt:x.activated_at,activeMembers:counts.get(String(x.id))||0,expiresAt:x.metadata?.expires_at||null,trialDays:x.metadata?.trial_days||null,expired:expiredLicense('tester',x.metadata)}))})}
if(action==='invite'){const token=String(req.headers.get('x-weddly-member')||b.memberToken||'').trim();if(token.length<40)return json({ok:false,error:'invalid_member'},401);const inviteCode=secret(),expiresAt=new Date(Date.now()+7*86400000).toISOString();const {data,error}=await db.rpc('create_weddly_partner_invite',{p_member_hash:await sha256(token),p_invite_hash:await sha256(inviteCode),p_expires_at:expiresAt});if(error)return rpcError(error);const row=data?.[0];if(!row)return json({ok:false,error:'server_error'},500);return json({ok:true,inviteCode,expiresAt:row.expires_at},201)}
if(action==='join'){const inviteCode=String(b.inviteCode||'').trim();if(inviteCode.length<40)return json({ok:false,error:'invalid_invite'},404);const memberToken=secret();const {data,error}=await db.rpc('join_weddly_partner_invite',{p_invite_hash:await sha256(inviteCode),p_member_hash:await sha256(memberToken)});if(error)return rpcError(error);const row=data?.[0];if(!row)return json({ok:false,error:'server_error'},500);return json({ok:true,weddingId:row.wedding_id,role:'partner',memberToken},201)}
if(action==='status'){const c=await memberContext(db,req,b);if(!c)return json({ok:false,error:'invalid_member'},401);const {count,error:ce}=await db.from('wedding_members').select('id',{head:true,count:'exact'}).eq('license_id',c.member.license_id).eq('role','partner').eq('status','active');if(ce)throw ce;await db.from('wedding_members').update({last_seen_at:new Date().toISOString()}).eq('id',c.member.id);const win=await weddingWindow(db,c.license);return json({ok:true,weddingId:c.member.wedding_id,role:c.member.role,partnerJoined:(count||0)>0,owner:c.license.source==='internal_owner',tester:c.license.source==='tester',expiresAt:c.license.metadata?.expires_at||win?.expiresAt||null,expiryRule:win?'wedding_plus_90':(c.license.metadata?.expires_at?'fixed':null)})}
return json({ok:false,error:'invalid_action'},400)}catch(e){const m=String((e as Error)?.message||'');if(m==='body_too_large')return json({ok:false,error:m},413);if(m==='invalid_json')return json({ok:false,error:m},400);if(m==='gumroad_verify_unavailable'||m.startsWith('etsy_'))return json({ok:false,error:'verification_unavailable'},503);console.warn(e);return json({ok:false,error:'server_error'},500)}});